title: Your awesome title
author: jbmagination
email: my-emaii-is@my.house
description: > # this means to ignore newlines until "baseurl:"
  hi please go away from this place its cringe
  
# social links
twitter_username: I DONT EVEN HAVE ONE
github_username:  jbmagination

show_excerpts: true # set to false to remove excerpts on the homepage

theme: jekyll-theme-cayman
